[package]
name = "farmfe_toolkit"
version = "0.0.17"
edition = "2021"
authors = ["brightwu(吴明亮) <1521488775@qq.com>"]
license = "MIT"
description = "Toolkit for farm."
homepage = "https://farmfe.org"
repository = "https://github.com/farm-fe/farm"
documentation = "https://docs.rs/farmfe_toolkit"

[features]
# full = [
#   "swc_ecma_parser",
#   "swc_ecma_visit",
#   "swc_ecma_codegen",
#   "swc_ecma_transforms",
# ]

[dependencies]
farmfe_core = { path = "../core", version = "0.7.3" }
farmfe_utils = { path = "../utils", version = "0.1.6" }
farmfe_testing_helpers = { path = "../testing_helpers", version = "0.0.15" }
swc_ecma_parser = { version = "4.0.0" }
swc_ecma_visit = { version = "3.0.0" }
swc_ecma_codegen = { version = "3.0.0" }
swc_typescript = { version = "3.0.0" }
swc_ecma_transforms = { version = "4.0.0", features = [
  "module",
  "typescript",
  "react",
  "concurrent",
] }
swc_ecma_preset_env = { version = "4.0.0" }
preset_env_base = { version = "1.0.0" }
swc_css_parser = { version = "3.0.0" }
swc_css_visit = { version = "3.0.0" }
swc_css_codegen = { version = "3.0.0" }
swc_css_minifier = { version = "3.0.0" }
swc_css_modules = { version = "3.0.0" }
swc_css_prefixer = { version = "3.0.0" }
swc_html_parser = { version = "3.0.0" }
swc_html_visit = { version = "3.0.0" }
swc_html_codegen = { version = "3.0.0" }
swc_html_minifier = { version = "4.0.0" }
swc_error_reporters = { version = "4.0.0" }
swc_atoms = { version = "2.0.0" }
swc_ecma_transforms_base = "4.0.1"
swc_ecma_minifier = "4.0.0"
swc_ecma_utils = "4.0.0"
sourcemap = "9.0.0"
anyhow = { version = "1.0.90", features = ["backtrace"] }
itertools = "0.13.0"
