[package]
name = "farmfe_toolkit"
version = "0.0.14"
edition = "2021"
authors = ["brightwu(吴明亮) <1521488775@qq.com>"]
license = "MIT"
description = "Toolkit for farm."
homepage = "https://farmfe.org"
repository = "https://github.com/farm-fe/farm"
documentation = "https://docs.rs/farmfe_toolkit"

[features]
# full = [
#   "swc_ecma_parser",
#   "swc_ecma_visit",
#   "swc_ecma_codegen",
#   "swc_ecma_transforms",
# ]

[dependencies]
farmfe_core = { path = "../core", version = "0.7.0" }
farmfe_utils = { path = "../utils", version = "0.1.6" }
farmfe_toolkit_plugin_types = { path = "../toolkit_plugin_types", version = "0.0.21" }
farmfe_testing_helpers = { path = "../testing_helpers", version = "0.0.14" }
swc_ecma_parser = { version = "0.146.12" }
swc_ecma_visit = { version = "0.101.0" }
swc_ecma_codegen = { version = "0.151.1" }
swc_ecma_transforms = { version = "0.232.1", features = [
  "module",
  "typescript",
  "react",
  "concurrent",
] }
swc_ecma_preset_env = { version = "0.210.0" }
preset_env_base = { version = "0.5.1" }
swc_css_parser = { version = "0.151.0" }
swc_css_visit = { version = "0.140.0" }
swc_css_codegen = { version = "0.152.0" }
swc_css_minifier = { version = "0.117.1" }
swc_css_modules = { version = "0.30.0" }
swc_css_prefixer = { version = "0.155.0" }
swc_html_parser = { version = "0.40.0" }
swc_html_visit = { version = "0.34.0" }
swc_html_codegen = { version = "0.43.0" }
swc_html_minifier = { version = "0.139.1" }
swc_error_reporters = { version = "0.18.1" }
swc_atoms = { version = "0.6.7" }
swc_ecma_transforms_base = "0.140.3"
swc_ecma_minifier = "0.197.3"
swc_ecma_utils = "0.130.3"
lazy_static = "1.4.0"
sourcemap = "8.0.1"
anyhow = { version = "1.0.40", features = ["backtrace"] }
