[package]
name = "farmfe_toolkit"
version = "0.0.8"
edition = "2021"
authors = ["brightwu(吴明亮) <1521488775@qq.com>"]
license = "MIT"
description = "Toolkit for farm."
homepage = "https://farmfe.org"
repository = "https://github.com/farm-fe/farm"
documentation = "https://docs.rs/farmfe_toolkit"

[features]
# full = [
#   "swc_ecma_parser",
#   "swc_ecma_visit",
#   "swc_ecma_codegen",
#   "swc_ecma_transforms",
# ]

[dependencies]
farmfe_core = { path = "../core", version = "0.5.1" }
farmfe_utils = { path = "../utils", version = "0.1.4" }
farmfe_toolkit_plugin_types = { path = "../toolkit_plugin_types", version = "0.0.15" }
farmfe_testing_helpers = { path = "../testing_helpers", version = "0.0.8" }
swc_ecma_parser = { version = "0.143.16" }
swc_ecma_visit = { version = "0.98.7" }
swc_ecma_codegen = { version = "0.148.17" }
swc_ecma_transforms = { version = "0.229.18", features = [
  "module",
  "typescript",
  "react",
  "concurrent",
] }
swc_ecma_preset_env = { version = "0.206.17" }
preset_env_base = { version = "0.4.12" }
swc_css_parser = { version = "0.150.30" }
swc_css_visit = { version = "0.139.21" }
swc_css_codegen = { version = "0.151.31" }
swc_css_minifier = { version = "0.116.32" }
swc_css_modules = { version = "0.29.34" }
swc_css_prefixer = { version = "0.153.35" }
swc_html_parser = { version = "0.39.26" }
swc_html_visit = { version = "0.33.19" }
swc_html_codegen = { version = "0.42.27" }
swc_html_minifier = { version = "0.134.19" }
swc_error_reporters = { version = "=0.17.19" }
swc_atoms = { version = "0.6.5" }
swc_ecma_transforms_base = "0.137.16"
swc_ecma_minifier = "0.192.18"
swc_ecma_utils = "0.127.13"
lazy_static = "1.4.0"
sourcemap = "8.0.1"
anyhow = { version = "1.0.40", features = ["backtrace"] }
