[package]
name = "farmfe_toolkit"
version = "0.0.1"
edition = "2021"

[features]
# full = [
#   "swc_ecma_parser",
#   "swc_ecma_visit",
#   "swc_ecma_codegen",
#   "swc_ecma_transforms",
# ]

[dependencies]
farmfe_core = { path = "../core" }
swc_ecma_parser = { version = "0.117.4" }
swc_ecma_visit = { version = "0.76.5" }
swc_ecma_codegen = { version = "0.121.4" }
swc_ecma_transforms = { version = "0.183.3", features = [
  "module",
  "typescript",
] }
swc_css_parser = { version = "0.116.0" }
swc_css_visit = { version = "0.106.0" }
swc_css_codegen = { version = "0.117.0" }
swc_html_parser = { version = "0.29.4" }
swc_html_visit = { version = "0.24.4" }
swc_html_codegen = { version = "0.32.4" }
glob = "0.3"
