[package]
name = "farmfe_toolkit"
version = "0.0.4"
edition = "2021"
authors = ["brightwu(吴明亮) <1521488775@qq.com>"]
license = "MIT"
description = "Toolkit for farm."
homepage = "https://farmfe.org"
repository = "https://github.com/farm-fe/farm"
documentation = "https://docs.rs/farmfe_toolkit"

[features]
# full = [
#   "swc_ecma_parser",
#   "swc_ecma_visit",
#   "swc_ecma_codegen",
#   "swc_ecma_transforms",
# ]

[dependencies]
farmfe_core = { path = "../core", version = "0.4.3" }
farmfe_utils = { path = "../utils", version = "0.1.4" }
farmfe_toolkit_plugin_types = { path = "../toolkit_plugin_types", version = "0.0.11" }
farmfe_testing_helpers = { path = "../testing_helpers", version = "0.0.4" }
swc_ecma_parser = { version = "0.142.0" }
swc_ecma_visit = { version = "0.97.0" }
swc_ecma_codegen = { version = "0.147.0" }
swc_ecma_transforms = { version = "0.228.1", features = [
  "module",
  "typescript",
  "react",
  "concurrent",
] }
swc_ecma_preset_env = { version = "0.205.1" }
preset_env_base = { version = "0.4.10" }
swc_css_parser = { version = "0.150.23" }
swc_css_visit = { version = "0.139.15" }
swc_css_codegen = { version = "0.151.24" }
swc_css_minifier = { version = "0.116.25" }
swc_css_modules = { version = "0.29.27" }
swc_css_prefixer = { version = "0.153.27" }
swc_html_parser = { version = "0.39.18" }
swc_html_visit = { version = "0.33.13" }
swc_html_codegen = { version = "0.42.18" }
swc_html_minifier = { version = "0.133.1" }
swc_error_reporters = { version = "0.17.12" }
swc_atoms = { version = "0.6.5" }
swc_ecma_transforms_base = "0.136.0"
swc_ecma_minifier = "0.191.1"
swc_ecma_utils = "0.126.0"
lazy_static = "1.4.0"
sourcemap = "6.2.3"
anyhow = { version = "1.0.40", features = ["backtrace"] }
