[package]
name = "farmfe_toolkit"
version = "2.0.1"
edition = "2021"
authors = ["brightwu(吴明亮) <1521488775@qq.com>"]
license = "MIT"
description = "Toolkit for farm."
homepage = "https://farmfe.org"
repository = "https://github.com/farm-fe/farm"
documentation = "https://docs.rs/farmfe_toolkit"

[features]
# full = [
#   "swc_ecma_parser",
#   "swc_ecma_visit",
#   "swc_ecma_codegen",
#   "swc_ecma_transforms",
# ]

[dependencies]
farmfe_core = { path = "../core", version = "3.0.0" }
farmfe_utils = { path = "../utils", version = "2.0.0" }
farmfe_testing_helpers = { path = "../testing_helpers", version = "2.0.1" }
swc_ecma_parser = { version = "23.0.0" }
swc_ecma_visit = { version = "15.0.0" }
swc_ecma_codegen = { version = "17.0.0" }
swc_typescript = { version = "20.0.0" }
swc_ecma_transforms = { version = "29.0.0", features = [
  "module",
  "typescript",
  "react",
  "concurrent",
] }
swc_ecma_preset_env = { version = "30.0.0" }
preset_env_base = { version = "5.0.0" }
swc_css_parser = { version = "14.0.0" }
swc_css_visit = { version = "14.0.0" }
swc_css_codegen = { version = "14.0.0" }
swc_css_minifier = { version = "14.0.0" }
swc_css_modules = { version = "14.0.0" }
swc_css_prefixer = { version = "17.0.0" }
swc_html_parser = { version = "14.0.0" }
swc_html_visit = { version = "14.0.0" }
swc_html_codegen = { version = "15.0.0" }
swc_html_minifier = { version = "30.0.0" }
swc_error_reporters = { version = "16.0.1" }
swc_atoms = { version = "7.0.0" }
swc_ecma_transforms_base = { version = "25.0.0", features = ["concurrent"] }
swc_ecma_minifier = { version = "30.0.0", features = ["concurrent"] }
swc_ecma_utils = { version = "21.0.0", features = ["concurrent"] }
swc_sourcemap = "9.3.4"
anyhow = { version = "1.0.90", features = ["backtrace"] }
itertools = "0.14.0"
par-core = { version = "2.0.0", features = ["chili"] }
bytes-str = { workspace = true }
