[workspace]
members = ["crates/*", "packages/create-farm", "rust-plugins/*"]
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://farmfe.org"
license = "MIT"
repository = "https://github.com/farm-fe/farm"

[profile.release-publish]
inherits = "release"
codegen-units = 1
lto = "thin"
opt-level = 3
strip = true
panic = "abort"

[profile.ci-test]
inherits = "release"
# opt-level = 0
# debug = 2
# lto = false
# codegen-units = 16
