[workspace]
release = true
git_release_enable = false

[[package]]
name = "farmfe_node"
release = false

[[package]]
name = "farmfe_plugin_dts"
release = false

[[package]]
name = "farmfe_plugin_sass"
release = false

[[package]]
name = "farmfe_plugin_react"
release = false

[[package]]
name = "create_farm_node"
release = false


# [[package]]
# name = "farmfe_utils"
# release = true

# [[package]]
# name = "farmfe_macro_cache_item"
# release = true

# [[package]]
# name = "farmfe_toolkit_plugin_types"
# release = true

# [[package]]
# name = "farmfe_macro_plugin"
# release = true
