[workspace]
release = true
git_release_enable = false

[[package]]
name = "farmfe_node"
release = false

[[package]]
name = "farmfe_plugin_dts"
release = false

[[package]]
name = "farmfe_plugin_sass"
release = false

[[package]]
name = "farmfe_plugin_react"
release = false

[[package]]
name = "create_farm_node"
release = false


[[package]]
name = "farmfe_utils"
publish_no_verify = true
