[workspace]
release = false
git_release_enable = false

[[package]]
name = "farmfe_core"
release = true

[[package]]
name = "farmfe_utils"
release = true

[[package]]
name = "farmfe_macro_cache_item"
release = true

[[package]]
name = "farmfe_toolkit_plugin_types"
release = true

[[package]]
name = "farmfe_macro_plugin"
release = true
