[package]
name = "farmfe_swc_transformer_import_glob"
version = "0.0.1"
edition = "2021"
authors = ["brightwwu(吴明亮) <1521488775@qq.com>"]
description = "farm utils"
license = "MIT"

[dependencies]
glob = "0.3"
relative-path = "1.7"
swc_ecma_ast = { version = "0.107.2", features = ["rkyv-impl", "serde-impl"] }
swc_common = { version = "0.31.18", features = ["concurrent", "sourcemap"] }
swc_ecma_visit = { version = "0.93.2" }
