[package]
name = "farmfe_swc_transformer_import_glob"
version = "0.0.1"
edition = "2021"
authors = ["brightwwu(吴明亮) <1521488775@qq.com>"]
description = "farm swc tranformer for vite-style import.meta.glob"
license = "MIT"

[dependencies]
farmfe_core = { path = "../core", version = "0.3.0" }
farmfe_toolkit = { path = "../toolkit", version = "0.0.1" }
farmfe_utils = { path = "../utils", version = "0.1.2" }
farmfe_testing_helpers = { path = "../testing_helpers", version = "0.0.1" }
