[package]
edition = "2021"
name = "farmfe_plugin_replace_dirname"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "*", path = "../../crates/core" }
farmfe_macro_plugin = { version = "*", path = "../../crates/macro_plugin" }
farmfe_toolkit = { version = "*", path = "../../crates/toolkit" }
regex = "1.7.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
url = "2.3.1"
