[package]
name = "farmfe_toolkit_plugin_types"
version = "2.0.1"
edition = "2021"
authors = ["brightwu(吴明亮) <1521488775@qq.com>"]
license = "MIT"
description = "builtin tooltips for farm plugins"

[dependencies]
farmfe_core = { version = "2.1.0", path = "../core" }
lazy_static = "1.4.0"
libloading = "0.7.0"
