[package]
name = "farmfe_testing_helpers"
version = "0.0.14"
edition = "2021"
authors = ["brightwu(吴明亮) <1521488775@qq.com>"]
license = "MIT"
description = "Testing helpers for farm."
homepage = "https://farmfe.org"
repository = "https://github.com/farm-fe/farm"
documentation = "https://docs.rs/farmfe_plugin_define"

[dependencies]
farmfe_core = { path = "../core", version = "0.7.0" }
