[package]
edition = "2021"
name = "create_farm_node"
version = "0.1.1"
authors = ["Erkelost"]
license = "MIT"
description = "Create Farm cli tool"
homepage = "https://farmfe.org"
repository = "https://github.com/farm-fe/farm"


[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.15.2", default-features = false, features = [
  "napi4",
  "serde-json",
] }
napi-derive = "2.15.2"
create-farm = { version = "0.1.1", path = "../../crates/create-farm-rs" }

[build-dependencies]
napi-build = "2.0.1"
