[package]
edition = "2021"
name = "farmfe_plugin_sass"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "*", path = "../../crates/core" }
farmfe_macro_plugin = { version = "*", path = "../../crates/macro_plugin" }
farmfe_toolkit_plugin_types = { version = "*", path = "../../crates/toolkit_plugin_types" }
farmfe_toolkit = { path = "../../crates/toolkit" }
sass-embedded = { version = "0.6.2", features = ["legacy", "serde"] }
serde = { version = "1.0", features = ["derive"] }
grass = { version = "0.12.4"}

[dev-dependencies]
farmfe_testing_helpers = { path = "../../crates/testing_helpers" }
farmfe_compiler = { path = "../../crates/compiler" }
