[package]
name = "farmfe_core"
version = "0.2.0"
edition = "2021"
authors = ["brightwu(吴明亮) <1521488775@qq.com>"]
license = "MIT"
description = "Core types and data structures for farm."

[dependencies]
farmfe_macro_cache_item = { version = "0.1.0", path = "../macro_cache_item" }
farmfe_utils = { version = "0.1.0", path = "../utils" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
relative-path = "1.7"
dashmap = "5.0"
blake2 = "0.10"
hex = "0.4"
rkyv = { version = "0.7.42" }
rkyv_dyn = "0.7.42"
rkyv_typename = "0.7.42"
ptr_meta = "0.1.4"
thiserror = "1.0"
rayon = "1.5"
petgraph = "0.6"
bytecheck = "0.7.0"
downcast-rs = "1.2"
glob = "0.3"
swc_ecma_ast = { version = "0.110.17", features = ["rkyv-impl", "serde-impl"] }
swc_ecma_parser = { version = "0.141.37" }
swc_common = { version = "0.33.12", features = [
  "concurrent",
  "sourcemap",
  "rkyv-impl",
] }
swc_css_ast = { version = "0.140.14", features = ["rkyv-impl"] }
swc_css_prefixer = { version = "0.153.25" }
swc_ecma_preset_env = { version = "0.204.19" }
preset_env_base = { version = "0.4.9" }
swc_html_ast = { version = "0.33.12", features = ["rkyv-impl"] }
heck = "0.4.1"
puffin = { version = "0.18.0", features = [
  "packing",
  "lz4",
  "serialization",
], optional = true }
regex = "1.7.3"
enhanced-magic-string = { version = "0.0.12" }

[features]
profile = ["dep:puffin"]
