[package]
edition = "2021"
name = "farmfe_plugin_yaml"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = {version = "*", path = "../../crates/core"}
farmfe_macro_plugin = {version = "*", path = "../../crates/macro_plugin"}
farmfe_toolkit_plugin_types = {version = "*", path = "../../crates/toolkit_plugin_types"}
globset = "0.4.14"
lazy_static = "1.5.0"
regex = "1.10.5"
serde = "1.0.203"
serde_yaml = "0.9.34"
