[package]
name = "farmfe_plugin_tree_shake"
version = "0.0.1"
edition = "2021"
authors = ["brightwu(吴明亮) <1521488775@qq.com>"]
description = "tree shake plugin for farmfe"
license = "MIT"

[dependencies]
farmfe_core = { path = "../core" }
farmfe_testing_helpers = { path = "../testing_helpers" }
farmfe_toolkit = { path = "../toolkit" }
farmfe_utils = { path = "../utils" }

[features]
profile = ["farmfe_core/profile"]
