name: Code Spell Check
on: [pull_request]

jobs:
  code-spell-check:
    name: Spell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install pnpm
        run: npm install -g pnpm@9.4.0
      - name: pnpm install
        run: pnpm install
      - name: Run Spell Check
        shell: bash
        run: npx cspell "**" --gitignore
