name: Plugin Sass CI
on:
  pull_request:
    paths:
      - 'rust-plugins/**'

jobs:
  call-rust-plugin-sass-build:
    uses: ./.github/workflows/rust-plugin-build.yaml
    with:
      root: rust-plugins/sass
      name: plugin-sass

  check-plugin-artifacts:
    name: Check Plugin Artifacts
    runs-on: ubuntu-latest
    needs: call-rust-plugin-sass-build
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: /tmp/artifacts
      - name: Check
        run: |
          for abi in linux-x64-gnu darwin-x64 win32-x64-msvc linux-arm64-musl linux-arm64-gnu darwin-arm64 win32-ia32-msvc win32-arm64-msvc
          do
            test -f /tmp/artifacts/${{ github.sha }}-${abi}-plugin-sass/index.farm
          done
